[build-system]
requires = ["hatchling",]
build-backend = "hatchling.build"

[project]
name = "hatch-foo-builder"
version = "0.0.1"
requires-python = ">=3.8"

[tool.hatch.build]
sources = ["src"]
only-packages = true

[project.entry-points.hatch]
foo = "foo_builder.hooks"
